'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/components/ui/toast';
import { parseAmountToMinorUnits } from '@/lib/money';

type FieldErrors = Record<string, string[] | undefined>;

const PAYMENT_METHOD_OPTIONS = [
  { value: 'cash', label: 'Cash' },
  { value: 'bank', label: 'Bank transfer' },
  { value: 'mobile_money', label: 'Mobile money' },
  { value: 'other', label: 'Other' },
];

interface RecordPaymentFormProps {
  students: { id: string; fullName: string; studentCode: string }[];
  terms: { id: string; label: string; isCurrent: boolean }[];
}

/**
 * Record money received. Append-only: the receipt number is generated by the
 * database and shown straight back to the person who took the money. After a
 * successful save the form keeps the student and term so a queue of payments
 * can be recorded without re-picking them.
 */
export function RecordPaymentForm({ students, terms }: RecordPaymentFormProps) {
  const router = useRouter();
  const toast = useToast();

  const [studentId, setStudentId] = useState('');
  const [termId, setTermId] = useState('');
  const [amount, setAmount] = useState('');
  const [method, setMethod] = useState('');
  const [reference, setReference] = useState('');
  const [notes, setNotes] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [errors, setErrors] = useState<FieldErrors>({});

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setErrors({});

    const localErrors: FieldErrors = {};
    if (!studentId) localErrors.studentId = ['Choose the student.'];
    if (!termId) localErrors.termId = ['Choose the term.'];
    if (!method) localErrors.method = ['Choose how the money was received.'];

    let amountMinor: number | null = null;
    if (!amount.trim()) {
      localErrors.amount = ['Enter the amount received.'];
    } else {
      try {
        amountMinor = parseAmountToMinorUnits(amount.trim());
      } catch {
        localErrors.amount = ['Enter a valid amount, e.g. 12,500.00'];
      }
    }

    if (Object.keys(localErrors).length > 0) {
      setErrors(localErrors);
      return;
    }

    setSubmitting(true);
    try {
      const response = await fetch('/api/fees/payments', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          studentId,
          termId,
          amount: amountMinor,
          method,
          reference: reference.trim() || null,
          notes: notes.trim() || null,
        }),
      });

      if (response.ok) {
        const body = (await response.json()) as { receiptNo: string };
        toast.success('Payment recorded', `Receipt ${body.receiptNo} saved to the ledger.`);
        setAmount('');
        setMethod('');
        setReference('');
        setNotes('');
        router.refresh();
        return;
      }

      const payload = (await response.json().catch(() => null)) as {
        error?: { message?: string; details?: FieldErrors };
      } | null;
      setErrors(payload?.error?.details ?? {});
      throw new Error(payload?.error?.message ?? 'Could not record the payment. Please try again.');
    } catch (err) {
      toast.error('Payment not recorded', err instanceof Error ? err.message : 'Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6" noValidate>
      {errors._form?.[0] ? <Alert variant="destructive" title={errors._form[0]} /> : null}

      <div className="grid gap-x-6 gap-y-4 sm:grid-cols-2">
        <div className="space-y-1.5">
          <Label htmlFor="payment-student">Student *</Label>
          <Select value={studentId || 'unset'} onValueChange={(v) => setStudentId(v === 'unset' ? '' : v)}>
            <SelectTrigger id="payment-student" aria-label="Student" aria-invalid={errors.studentId ? true : undefined}>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="unset" disabled>
                Choose a student…
              </SelectItem>
              {students.map((student) => (
                <SelectItem key={student.id} value={student.id}>
                  {student.fullName} · {student.studentCode}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.studentId ? (
            <p className="text-xs text-destructive" role="alert">
              {errors.studentId[0]}
            </p>
          ) : null}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="payment-term">Term *</Label>
          <Select value={termId || 'unset'} onValueChange={(v) => setTermId(v === 'unset' ? '' : v)}>
            <SelectTrigger id="payment-term" aria-label="Term" aria-invalid={errors.termId ? true : undefined}>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="unset" disabled>
                Choose a term…
              </SelectItem>
              {terms.map((term) => (
                <SelectItem key={term.id} value={term.id}>
                  {term.label}
                  {term.isCurrent ? ' (current)' : ''}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.termId ? (
            <p className="text-xs text-destructive" role="alert">
              {errors.termId[0]}
            </p>
          ) : null}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="payment-amount">Amount (NLe) *</Label>
          <Input
            id="payment-amount"
            inputMode="decimal"
            placeholder="0.00"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            aria-invalid={errors.amount ? true : undefined}
          />
          {errors.amount ? (
            <p className="text-xs text-destructive" role="alert">
              {errors.amount[0]}
            </p>
          ) : null}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="payment-method">Method *</Label>
          <Select value={method || 'unset'} onValueChange={(v) => setMethod(v === 'unset' ? '' : v)}>
            <SelectTrigger id="payment-method" aria-label="Payment method" aria-invalid={errors.method ? true : undefined}>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="unset" disabled>
                Choose a method…
              </SelectItem>
              {PAYMENT_METHOD_OPTIONS.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.method ? (
            <p className="text-xs text-destructive" role="alert">
              {errors.method[0]}
            </p>
          ) : null}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="payment-reference">Reference</Label>
          <Input
            id="payment-reference"
            value={reference}
            onChange={(e) => setReference(e.target.value)}
            placeholder="e.g. transfer reference, cheque number"
          />
          {errors.reference ? (
            <p className="text-xs text-destructive" role="alert">
              {errors.reference[0]}
            </p>
          ) : null}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="payment-notes">Notes</Label>
          <Textarea
            id="payment-notes"
            rows={2}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Anything worth recording with this payment."
          />
          {errors.notes ? (
            <p className="text-xs text-destructive" role="alert">
              {errors.notes[0]}
            </p>
          ) : null}
        </div>
      </div>

      <div className="flex items-center justify-end gap-3">
        <Button type="submit" disabled={submitting}>
          {submitting ? 'Saving…' : 'Record Payment'}
        </Button>
      </div>
    </form>
  );
}