import { redirect } from 'next/navigation';

import { can } from '@/server/auth/permissions';
import { getSessionUser } from '@/server/auth/bootstrap';
import { getPayrollRunDetail } from '@/server/portal/payroll';
import { formatMoney } from '@/lib/money';
import { formatDateTime } from '@/lib/format';
import { Alert } from '@/components/ui/alert';
import { Breadcrumb } from '@/components/ui/breadcrumb';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { EmptyState } from '@/components/ui/empty-state';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { PayrollStatusBadge } from '@/components/payroll/status-badge';
import { PayrollActions } from '@/components/payroll/payroll-actions';

/**
 * PAYROLL RUN DETAIL
 * ==================
 * The review screen for one run: the controlled workflow panel, the
 * reconciliation check, and the immutable line-by-line snapshot. Every figure
 * is read from the run's own snapshot - nothing joins back to live salary or
 * bank data, so what is shown here is exactly what would be paid.
 */
export default async function PayrollRunPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const user = await getSessionUser();
  if (!user) redirect('/login');

  if (!can(user, 'payroll:read')) {
    return (
      <EmptyState
        title="You cannot view payroll"
        description="Your role does not include payroll records. Ask the Proprietor if you need access."
      />
    );
  }

  const { id } = await params;
  const { run, items, validation } = await getPayrollRunDetail(user, id);

  return (
    <div className="space-y-6">
      <Breadcrumb items={[{ label: 'Payroll', href: '/payroll' }, { label: run.runCode }]} />

      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-2xl font-semibold tracking-tight">{run.runCode}</h1>
            <PayrollStatusBadge status={run.status} />
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            {run.period} · Revision {run.revision}
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            Generated by {run.generatedByName ?? 'system'} on {formatDateTime(run.generatedAt)}
          </p>
        </div>
      </div>

      {run.approvedAt ? (
        <p className="-mt-4 text-sm text-muted-foreground">
          Approved by {run.approvedByName ?? 'n/a'} on {formatDateTime(run.approvedAt)}
        </p>
      ) : null}
      {run.exportedAt ? (
        <p className="-mt-4 text-sm text-muted-foreground">
          Exported on {formatDateTime(run.exportedAt)}
        </p>
      ) : null}
      {run.archivedAt ? (
        <p className="-mt-4 text-sm text-muted-foreground">
          Archived on {formatDateTime(run.archivedAt)}
        </p>
      ) : null}

      {!validation.totalsReconcile ? (
        <Alert variant="destructive" title="Totals do not reconcile">
          The header totals do not match the payroll lines. This should never happen - the database
          refuses to commit such a run. Contact support and quote this run&apos;s code.
        </Alert>
      ) : null}

      {validation.itemsMissingBankDetails > 0 ? (
        <Alert variant="warning" title="Some employees cannot be paid by bank transfer">
          {validation.itemsMissingBankDetails}{' '}
          {validation.itemsMissingBankDetails === 1 ? 'line has' : 'lines have'} no bank details
          ({validation.missingBankEmployees.slice(0, 5).join(', ')}
          {validation.missingBankEmployees.length > 5
            ? ` +${validation.missingBankEmployees.length - 5} more`
            : ''}
          ). Add bank details before approving if this run must be exported to the bank.
        </Alert>
      ) : null}

      {run.reopenReason ? (
        <Alert variant="info" title="Why this run was reopened">
          {run.reopenReason}
        </Alert>
      ) : null}

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
        <RunStat label="Employees" value={String(run.employeeCount)} />
        <RunStat label="Gross" value={formatMoney(run.totalGross)} />
        <RunStat label="Deductions" value={formatMoney(run.totalDeductions)} />
        <RunStat label="Net pay" value={formatMoney(run.totalNet)} emphasize />
        <RunStat label="Employer costs" value={formatMoney(run.totalEmployerCosts)} />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Workflow</CardTitle>
          <CardDescription>
            Calculated → review → approve → export → archive. Each step is audited.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <PayrollActions
            runId={run.runId}
            runCode={run.runCode}
            status={run.status}
            periodLabel={run.period}
            generatedBy={run.generatedBy}
            currentUserId={user.id}
            canApprove={can(user, 'payroll:approve')}
            canReopen={can(user, 'payroll:reopen')}
            canExport={can(user, 'payroll:export')}
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Payroll lines</CardTitle>
          <CardDescription>
            Immutable snapshot of who is paid, how much, and to which account.
          </CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Employee</TableHead>
                <TableHead>Position</TableHead>
                <TableHead className="text-right">Basic</TableHead>
                <TableHead className="text-right">Allowances</TableHead>
                <TableHead className="text-right">Deductions</TableHead>
                <TableHead className="text-right">Gross</TableHead>
                <TableHead className="text-right">Net</TableHead>
                <TableHead>Bank</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((item) => (
                <TableRow key={item.id}>
                  <TableCell>
                    <div>
                      <p className="font-medium">{item.employeeName}</p>
                      <p className="text-xs text-muted-foreground">{item.employeeCode}</p>
                    </div>
                  </TableCell>
                  <TableCell>
                    {item.position}
                    {item.department ? (
                      <span className="text-xs text-muted-foreground"> · {item.department}</span>
                    ) : null}
                  </TableCell>
                  <TableCell className="text-right tabular-nums">
                    {formatMoney(item.basicSalary)}
                  </TableCell>
                  <TableCell className="text-right tabular-nums">
                    {formatMoney(item.allowances)}
                  </TableCell>
                  <TableCell className="text-right tabular-nums">
                    {formatMoney(item.deductions)}
                  </TableCell>
                  <TableCell className="text-right tabular-nums">
                    {formatMoney(item.gross)}
                  </TableCell>
                  <TableCell className="text-right font-medium tabular-nums">
                    {formatMoney(item.net)}
                  </TableCell>
                  <TableCell>
                    {item.bank ? (
                      <div className="text-sm">
                        <p>{item.bank.bankName}</p>
                        <p className="tabular-nums text-muted-foreground">
                          {item.bank.accountName} · {item.bank.accountNumber}
                        </p>
                      </div>
                    ) : (
                      <span className="text-sm text-warning">No bank details</span>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          {items.length === 0 ? (
            <p className="px-4 py-8 text-center text-sm text-muted-foreground">
              This run has no payroll lines.
            </p>
          ) : null}
        </CardContent>
      </Card>

      {run.notes ? (
        <Card>
          <CardHeader>
            <CardTitle>Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="whitespace-pre-line text-sm text-muted-foreground">{run.notes}</p>
          </CardContent>
        </Card>
      ) : null}
    </div>
  );
}

function RunStat({
  label,
  value,
  emphasize = false,
}: {
  label: string;
  value: string;
  emphasize?: boolean;
}) {
  return (
    <div className="rounded-lg border bg-card p-4">
      <p className="text-xs font-medium text-muted-foreground">{label}</p>
      <p
        className={
          emphasize
            ? 'mt-1 text-xl font-semibold tabular-nums'
            : 'mt-1 text-xl tabular-nums'
        }
      >
        {value}
      </p>
    </div>
  );
}