import { redirect } from 'next/navigation';

import { can } from '@/server/auth/permissions';
import { getSessionUser } from '@/server/auth/bootstrap';
import { listFeeStudents, listFeesTerms } from '@/server/portal/fees';
import { Breadcrumb } from '@/components/ui/breadcrumb';
import { Card, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { RecordPaymentForm } from '@/components/fees/record-payment-form';

/**
 * RECORD FEE PAYMENT
 * Gate: only roles with `fees:record` may open the form. The route is not in
 * the sidebar for other roles, but a typed URL must still be refused.
 */
export default async function RecordFeePaymentPage() {
  const user = await getSessionUser();
  if (!user) redirect('/login');

  if (!can(user, 'fees:record')) {
    return (
      <Card className="mx-auto max-w-lg">
        <CardHeader>
          <CardTitle>You cannot record payments</CardTitle>
          <CardDescription>
            Your role does not include receiving fee payments. Ask the Proprietor if you need this
            access.
          </CardDescription>
        </CardHeader>
      </Card>
    );
  }

  const [students, terms] = await Promise.all([listFeeStudents(user), listFeesTerms(user)]);

  return (
    <div className="space-y-6">
      <Breadcrumb items={[{ label: 'Fees', href: '/fees' }, { label: 'Record Payment' }]} />
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Record a fee payment</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Money received against a student&apos;s term. The receipt number is generated by the
          database and printed on the receipt you give the parent.
        </p>
      </div>

      <RecordPaymentForm students={students} terms={terms} />
    </div>
  );
}