/**
 * THE REPOSITORY BOUNDARY
 * =======================
 * Everything above this line (services, routes, UI) depends on these
 * interfaces. Everything below it depends on PostgreSQL.
 *
 * DESIGN CHANGE FROM THE GOOGLE SHEETS DESIGN
 * -------------------------------------------
 * The previous version of this file had:
 *
 *     findWhere(predicate: (row: T) => boolean): Promise<T[]>
 *
 * which is unworkable against a real database, because a JavaScript function
 * cannot be pushed into SQL. It would have forced Postgres to return every row
 * and then filtered them in Node - exactly the "one query per table row"
 * anti-pattern the specification warns against, and fatal for a staff list of
 * any size.
 *
 * Filtering is therefore expressed as DATA (a `Filter` object) so it becomes
 * a `WHERE` clause with an index behind it. This is a genuine redesign of the
 * interface, not a rename.
 *
 * ARCHITECTURAL RULE: no file outside `src/server/repositories/postgres/` and
 * `src/server/db/` may import `pg`. ESLint enforces it.
 */

export type { MinorUnits } from '../db/money';

export interface Page<T> {
  rows: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

/**
 * Composable filter. Values combine with AND; `in` and `between` are the
 * array forms. `search` is a case-insensitive substring match across the
 * table's configured search columns.
 */
export interface Filter {
  eq?: Record<string, string | number | boolean | null | undefined>;
  in?: Record<string, Array<string | number>>;
  between?: Record<string, [string | number, string | number]>;
  /** Substring match, case-insensitive. */
  search?: { term: string; fields: string[] };
  /** Alias of `between` for date columns, for readability at call sites. */
  dateBetween?: Record<string, [string, string]>;
  /** Negation, e.g. `notIn: { status: ['terminated'] }`. */
  notIn?: Record<string, Array<string | number>>;
}

export interface ListOptions {
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDir?: 'asc' | 'desc';
  filter?: Filter;
  /** Columns to select. Omit for all. */
  select?: string[];
  /** Load a related entity by foreign key. */
  include?: string[];
}

export interface Aggregation {
  /** e.g. 'net', 'amount', 'basic_salary' */
  column: string;
  fn: 'sum' | 'avg' | 'min' | 'max' | 'count';
  alias?: string;
}

export interface AggregateResult {
  value: number;
}

/**
 * Read/write contract for one table.
 *
 * Deliberately small. Anything requiring joins, aggregation, or multi-step
 * logic belongs in a service or a dedicated named query, so the interface
 * stays honest about what a table adapter can do.
 */
export interface Repository<T extends { id: string }> {
  readonly entityName: string;
  readonly tableName: string;

  list(options?: ListOptions): Promise<Page<T>>;
  count(options?: ListOptions): Promise<number>;
  getById(id: string): Promise<T | null>;
  getByIds(ids: string[]): Promise<T[]>;
  /** Single equality lookup on an indexed column. */
  findOneBy(column: string, value: string | number): Promise<T | null>;

  create(input: NewRecord<T>): Promise<T>;
  update(id: string, patch: Partial<T>): Promise<T>;
  /** One round trip for the whole batch. */
  bulkCreate(inputs: Array<NewRecord<T>>): Promise<T[]>;

  /**
   * Aggregation for reports, e.g. sum of payroll net for a period.
   * Runs in the database, not in Node.
   */
  aggregate(aggregation: Aggregation, options?: ListOptions): Promise<number>;
}

/** A record being created: the id is generated by the database. */
export type NewRecord<T> = Omit<T, 'id' | 'createdAt' | 'updatedAt'> & {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
};

/**
 * Contexts a repository may run in. The adapter never chooses; the caller
 * does, via withUserContext / withServiceContext in db/transaction.ts.
 */
export type QueryContext = 'user' | 'service' | 'system';

export const DEFAULT_PAGE_SIZE = 25;
export const MAX_PAGE_SIZE = 200;

/** Clamp pagination so a client cannot ask for the whole table. */
export function normaliseListOptions(options: ListOptions = {}): {
  page: number;
  pageSize: number;
  sortDir: 'asc' | 'desc';
  offset: number;
} {
  const page = Math.max(1, Math.trunc(options.page ?? 1));
  const requested = Math.trunc(options.pageSize ?? DEFAULT_PAGE_SIZE);
  const pageSize = Math.min(MAX_PAGE_SIZE, Math.max(1, requested));
  const sortDir = options.sortDir ?? 'asc';
  return { page, pageSize, sortDir, offset: (page - 1) * pageSize };
}
